version: '3.8'

# services:
#   api:
#     build: .
#     container_name: my-node-app
#     ports:
#       - "3000:3000"
#     environment:
#       - DB_HOST=db
#       - DB_USER=root
#       - DB_PASSWORD=password
#       - DB_NAME=test_db
#     depends_on:
#       - db


#   db:
#     image: mysql:8.0
#     environment:
#       - MYSQL_ROOT_PASSWORD=password
#       - MYSQL_DATABASE=test_db
#     ports:
#       - "3306:3306"
#     volumes:
#       - mysql-data:/var/lib/mysql
#       - ./init.sql:/docker-entrypoint-initdb.d/init.sql

# volumes:
#   mysql-data:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     environment:
#       - DB_HOST=dev_test-db-1  # Nome do serviço do MySQL no Docker
#       - DB_PORT=3306
#       - DB_USER=root
#       - DB_PASSWORD=root
#       - DB_NAME=test
#     ports:
#       - "3000:3000"
#     depends_on:
#       - dev_test-db-1

#   dev_test-db-1:
#     image: mysql:8.0
#     environment:
#       MYSQL_ROOT_PASSWORD: root
#       MYSQL_DATABASE: test
#     ports:
#       - "3306:3306"

services:
  my-node-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    command: ["node", "dist/index.js"]

  dev_test-db-1:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: